export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  teamsWebhookUrl: process.env.TEAMS_WEBHOOK_URL ?? "",
  msGraphUsername: process.env.MS_GRAPH_USERNAME ?? "",
  msGraphPassword: process.env.MS_GRAPH_PASSWORD ?? "",
  msGraphClientId: process.env.MS_GRAPH_CLIENT_ID ?? "1fec8e78-bce4-4aaf-ab1b-5451cc387264",
  qboClientId: process.env.QBO_CLIENT_ID ?? "",
  qboClientSecret: process.env.QBO_CLIENT_SECRET ?? "",
  sevenShiftsCkAccessToken: process.env.SEVEN_SHIFTS_CK_ACCESS_TOKEN ?? "",
};
